
BACKBONE_DICT = {
    'CLIP': 512,
    'PLIP': 512,
    'MobileNetV3': 1280,
    'mobilenetv3': 1280,
    'ProvGigaPath': 1536,
    'CONCH': 512,
    'UNI': 1024
}

LABEL_COL_DICT = {
    # 'stage': 'ajcc_pathologic_stage',
    'subtype': 'PAM50_and_Claudin-low_(CLOW)_Molecular_Subtype',
    'Molecular_Subtype': 'Molecular_Subtype',  # this is the same as subtype
    'IHC_HER2': 'IHC_HER2',
    'HistoAnno': 'HistoAnno',
    'CLS_Molecular_Subtype': 'CLS_Molecular_Subtype',  # this is the same as subtype
    'CLS_IHC_HER2': 'CLS_IHC_HER2',
    'CLS_HistoAnno': 'CLS_HistoAnno',
    'SurvivalCls': 'disc_label',
    'TP53': 'TP53',
    'PIK3CA': 'PIK3CA',
    'KRAS': 'KRAS',
    'CDH1_cls': 'CDH1_cls',
    'GATA3_cls': 'GATA3_cls',
    'PIK3CA_cls': 'PIK3CA_cls',
    'TP53_cls': 'TP53_cls',
    'KRAS_cls': 'KRAS_cls',
    'ARID1A_cls': 'ARID1A_cls',
    'PIK3R1_cls': 'PIK3R1_cls',
    'PTEN_cls': 'PTEN_cls',
    'APC_cls': 'APC_cls',
    'ATRX_cls': 'ATRX_cls',
    'IDH1_cls': 'IDH1_cls',
    'BRAF_cls': 'BRAF_cls'
}

IGNORE_INDEX_DICT = {
    # 'stage': 3,
    'subtype': -100,
    'Molecular_Subtype': 4,
    'IHC_HER2': 2,
    'HistoAnno': -100,
    'CLS_Molecular_Subtype': 4,
    'CLS_IHC_HER2': 2,
    'CLS_HistoAnno': -100,
    'SurvivalCls': -100,
    'TP53': 2,
    'PIK3CA': 2,
    'KRAS': 2,
    'CDH1_cls': 2,
    'GATA3_cls': 2,
    'PIK3CA_cls': 2,
    'TP53_cls': 2,
    'KRAS_cls': 2,
    'ARID1A_cls': 2,
    'PIK3R1_cls': 2,
    'PTEN_cls': 2,
    'APC_cls': 2,
    'ATRX_cls': 2,
    'IDH1_cls': 2,
    'BRAF_cls': 2
}


PAN_CANCER_SITES = ['BRCA',
                    'PAAD',
                    'CHOL',
                    'UCS',
                    'DLBC',
                    'UVM',
                    'UCEC',
                    'MESO',
                    'ACC',
                    'KICH',
                    'THYM',
                    'TGCT',
                    'PCPG',
                    'ESCA',
                    'SARC',
                    'CESC',
                    'PRAD',
                    'THCA',
                    'OV',
                    'KIRC',
                    'BLCA',
                    'STAD',
                    'SKCM',
                    'READ',
                    'LUSC',
                    'LUAD',
                    'LIHC',
                    'LGG',
                    'KIRP',
                    'HNSC',
                    'COAD',
                    'GBM']



CLASSIFICATION_DICT = {
    'CDH1_cls': ['Gain_Or_Unknown_Or_NaN', 'Loss', 'Other'],
    'GATA3_cls': ['Gain_Or_Unknown_Or_NaN', 'Loss', 'Other'],
    'PIK3CA_cls': ['Loss_Or_Unknown_Or_NaN', 'Gain', 'Other'],
    'TP53_cls': ['Gain_Or_Unknown_Or_NaN', 'Loss', 'Other'],
    'KRAS_cls': ['Loss_Or_Unknown_Or_NaN', 'Gain', 'Other'],
    'ARID1A_cls': ['Gain_Or_Unknown_Or_NaN', 'Loss', 'Other'],
    'PTEN_cls': ['Gain_Or_Unknown_Or_NaN', 'Loss', 'Other'],
    'BRAF_cls': ['Loss_Or_Unknown_Or_NaN', 'Gain', 'Other'],
    'APC_cls': ['Gain_Or_Unknown_Or_NaN', 'Loss', 'Other'],
    'ATRX_cls': ['Gain_Or_Unknown_Or_NaN', 'Loss', 'Other'],
    'IDH1_cls': ['Gain_Or_Unknown_Or_NaN', 'Loss_Or_Switch', 'Other']
}


REGRESSION_LIST = [
    'Cytotoxic_T_Lymphocyte',
    'TIDE_CAF',
    'TIDE_Dys',
    'TIDE_M2',
    'TIDE_MDSC',
    'HALLMARK_ADIPOGENESIS_sum',
    'HALLMARK_ALLOGRAFT_REJECTION_sum',
    'HALLMARK_ANDROGEN_RESPONSE_sum',
    'HALLMARK_ANGIOGENESIS_sum',
    'HALLMARK_APICAL_JUNCTION_sum',
    'HALLMARK_APICAL_SURFACE_sum',
    'HALLMARK_APOPTOSIS_sum',
    'HALLMARK_BILE_ACID_METABOLISM_sum',
    'HALLMARK_CHOLESTEROL_HOMEOSTASIS_sum',
    'HALLMARK_COAGULATION_sum',
    'HALLMARK_COMPLEMENT_sum',
    'HALLMARK_DNA_REPAIR_sum',
    'HALLMARK_E2F_TARGETS_sum',
    'HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION_sum',
    'HALLMARK_ESTROGEN_RESPONSE_EARLY_sum',
    'HALLMARK_ESTROGEN_RESPONSE_LATE_sum',
    'HALLMARK_FATTY_ACID_METABOLISM_sum',
    'HALLMARK_G2M_CHECKPOINT_sum',
    'HALLMARK_GLYCOLYSIS_sum',
    'HALLMARK_HEDGEHOG_SIGNALING_sum',
    'HALLMARK_HEME_METABOLISM_sum',
    'HALLMARK_HYPOXIA_sum',
    'HALLMARK_IL2_STAT5_SIGNALING_sum',
    'HALLMARK_IL6_JAK_STAT3_SIGNALING_sum',
    'HALLMARK_INFLAMMATORY_RESPONSE_sum',
    'HALLMARK_INTERFERON_ALPHA_RESPONSE_sum',
    'HALLMARK_INTERFERON_GAMMA_RESPONSE_sum',
    'HALLMARK_KRAS_SIGNALING_DN_sum',
    'HALLMARK_KRAS_SIGNALING_UP_sum',
    'HALLMARK_MITOTIC_SPINDLE_sum',
    'HALLMARK_MTORC1_SIGNALING_sum',
    'HALLMARK_MYC_TARGETS_V1_sum',
    'HALLMARK_MYC_TARGETS_V2_sum',
    'HALLMARK_MYOGENESIS_sum',
    'HALLMARK_NOTCH_SIGNALING_sum',
    'HALLMARK_OXIDATIVE_PHOSPHORYLATION_sum',
    'HALLMARK_P53_PATHWAY_sum',
    'HALLMARK_PANCREAS_BETA_CELLS_sum',
    'HALLMARK_PEROXISOME_sum',
    'HALLMARK_PI3K_AKT_MTOR_SIGNALING_sum',
    'HALLMARK_PROTEIN_SECRETION_sum',
    'HALLMARK_REACTIVE_OXYGEN_SPECIES_PATHWAY_sum',
    'HALLMARK_SPERMATOGENESIS_sum',
    'HALLMARK_TGF_BETA_SIGNALING_sum',
    'HALLMARK_TNFA_SIGNALING_VIA_NFKB_sum',
    'HALLMARK_UNFOLDED_PROTEIN_RESPONSE_sum',
    'HALLMARK_UV_RESPONSE_DN_sum',
    'HALLMARK_UV_RESPONSE_UP_sum',
    'HALLMARK_WNT_BETA_CATENIN_SIGNALING_sum',
    'HALLMARK_XENOBIOTIC_METABOLISM_sum'
]


MsigDB_Hallmark_list = [
    "HALLMARK_ADIPOGENESIS_sum",
    "HALLMARK_ALLOGRAFT_REJECTION_sum",
    "HALLMARK_ANDROGEN_RESPONSE_sum",
    "HALLMARK_ANGIOGENESIS_sum",
    "HALLMARK_APICAL_JUNCTION_sum",
    "HALLMARK_APICAL_SURFACE_sum",
    "HALLMARK_APOPTOSIS_sum",
    "HALLMARK_BILE_ACID_METABOLISM_sum",
    "HALLMARK_CHOLESTEROL_HOMEOSTASIS_sum",
    "HALLMARK_COAGULATION_sum",
    "HALLMARK_COMPLEMENT_sum",
    "HALLMARK_DNA_REPAIR_sum",
    "HALLMARK_E2F_TARGETS_sum",
    "HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION_sum",
    "HALLMARK_ESTROGEN_RESPONSE_EARLY_sum",
    "HALLMARK_ESTROGEN_RESPONSE_LATE_sum",
    "HALLMARK_FATTY_ACID_METABOLISM_sum",
    "HALLMARK_G2M_CHECKPOINT_sum",
    "HALLMARK_GLYCOLYSIS_sum",
    "HALLMARK_HEDGEHOG_SIGNALING_sum",
    "HALLMARK_HEME_METABOLISM_sum",
    "HALLMARK_HYPOXIA_sum",
    "HALLMARK_IL2_STAT5_SIGNALING_sum",
    "HALLMARK_IL6_JAK_STAT3_SIGNALING_sum",
    "HALLMARK_INFLAMMATORY_RESPONSE_sum",
    "HALLMARK_INTERFERON_ALPHA_RESPONSE_sum",
    "HALLMARK_INTERFERON_GAMMA_RESPONSE_sum",
    "HALLMARK_KRAS_SIGNALING_DN_sum",
    "HALLMARK_KRAS_SIGNALING_UP_sum",
    "HALLMARK_MITOTIC_SPINDLE_sum",
    "HALLMARK_MTORC1_SIGNALING_sum",
    "HALLMARK_MYC_TARGETS_V1_sum",
    "HALLMARK_MYC_TARGETS_V2_sum",
    "HALLMARK_MYOGENESIS_sum",
    "HALLMARK_NOTCH_SIGNALING_sum",
    "HALLMARK_OXIDATIVE_PHOSPHORYLATION_sum",
    "HALLMARK_P53_PATHWAY_sum",
    "HALLMARK_PANCREAS_BETA_CELLS_sum",
    "HALLMARK_PEROXISOME_sum",
    "HALLMARK_PI3K_AKT_MTOR_SIGNALING_sum",
    "HALLMARK_PROTEIN_SECRETION_sum",
    "HALLMARK_REACTIVE_OXYGEN_SPECIES_PATHWAY_sum",
    "HALLMARK_SPERMATOGENESIS_sum",
    "HALLMARK_TGF_BETA_SIGNALING_sum",
    "HALLMARK_TNFA_SIGNALING_VIA_NFKB_sum",
    "HALLMARK_UNFOLDED_PROTEIN_RESPONSE_sum",
    "HALLMARK_UV_RESPONSE_DN_sum",
    "HALLMARK_UV_RESPONSE_UP_sum",
    "HALLMARK_WNT_BETA_CATENIN_SIGNALING_sum",
    "HALLMARK_XENOBIOTIC_METABOLISM_sum"
]

HF_MODELS_DICT = {
    'resnet18': ['ResNetModel', 'microsoft/resnet-18', 'pooler_output'],
    'resnet50': ['ResNetModel', 'microsoft/resnet-50', 'pooler_output'],
    'beit': ['BeitModel', 'microsoft/beit-base-patch16-224-pt22k', 'pooler_output'],
    'bit': ['BitModel', 'google/bit-50', 'pooler_output', 'pooler_output'],
    'convnext': ['ConvNextModel', 'facebook/convnext-tiny-224', 'pooler_output'],
    # 'cvt': ['CvtModel', 'microsoft/cvt-13', 'cls_token_value'],
    # 'deit': ['DeiTModel', 'facebook/deit-base-distilled-patch16-224', 'pooler_output'],
    # 'dinat': ['DinatModel', 'shi-labs/dinat-mini-in1k-224'],
    # 'dpt': ['DPTModel', 'Intel/dpt-large', 'pooler_output'],
    # 'efficientformer': ['EfficientFormerModel', 'snap-research/efficientformer-l1-300'],
    # 'efficientnet': ['EfficientNetModel', 'google/efficientnet-b7'],
    # 'glpn': ['GLPNModel', 'vinvino02/glpn-kitti'],
    # 'imagegpt': ['ImageGPTModel', 'openai/imagegpt-small'],
    # 'levit': ['LevitModel', 'facebook/levit-128S', 'pooler_output'],
    'mobilenetv1': ['MobileNetV1Model', 'google/mobilenet_v1_1.0_224', 'pooler_output'],
    'mobilenetv2': ['MobileNetV2Model', 'google/mobilenet_v2_1.0_224', 'pooler_output'],
    'mobilevit': ['MobileViTModel', 'apple/mobilevit-small', 'pooler_output'],
    # 'nat': ['NatModel', 'shi-labs/nat-mini-in1k-224'],
    # 'poolformer': ['PoolFormerModel', 'sail/poolformer_s12'],
    # 'swin': ['SwinModel', 'microsoft/swin-tiny-patch4-window7-224', 'pooler_output'],
    'swinv2': ['Swinv2Model', 'microsoft/swinv2-tiny-patch4-window8-256', 'pooler_output'],
    'vit': ['ViTModel', 'google/vit-base-patch16-224-in21k', 'pooler_output'],
    'vithybrid': ['ViTHybridModel', 'google/vit-hybrid-base-bit-384', 'pooler_output'],
    # 'vitmae': ['ViTMAEModel', 'facebook/vit-mae-base'],
    # 'vitmsn': ['ViTMSNModel', 'facebook/vit-msn-small']
    'mobilenetv3': ['timm_mobilenetv3', '', 'flatten'],
    'CLIP': ['CLIPModel', 'openai/clip-vit-base-patch32', None],
    # 'PLIP': ['CLIPModel', 'vinid/plip', None],
    'PLIP': ['CLIPModel', './vinid_plip', None],
    'ProvGigaPath': ['timm_ProvGigaPath', '', None],
    'CONCH': ['CONCH', '', None],
    'UNI': ['UNI', '', None]
}












